"""
Ranking Shorts generator — a parallel content format to the clip pipeline.

Produces "Top 5" ranking compilation Shorts: 5 short portrait stock clips
(Pexels) stitched together with a title banner and timed rank-label overlays,
plus baked-in royalty-free background music (Pixabay).

The script (title + labels + per-rank search queries) is NOT generated by an
LLM at runtime — it is read from `ranker_scripts.json` on Google Drive, which the
user produces by pasting a fixed prompt into any LLM chat. See `script_source.py`.
"""
